log:
  loglevel: none
dns:
  servers:
    - 8.8.8.8
  queryStrategy: UseIPv4
inbounds:
  - port: 8888
    listen: 127.0.0.1
    protocol: vless
    settings:
      clients:
        - id: 0e059fce-d6c8-4cc2-9e11-9efff358f8b9
      decryption: none
    streamSettings:
      network: ws
outbounds:
  - protocol: freedom
    settings: {}
